/**
 * In-memory fallback mock data for ResilinkService
 * Replaces CSV seed files to ensure fast, deterministic, crash-free startup.
 */

module.exports = {
  "AIRecommendations": [
    {
      "ID": "REC-2026-B1",
      "title": "AI Recommended Network Design",
      "recommendedSupplier": "Supplier B (Munich Materials) with Supplier C backup",
      "recommendedPlant": "Plant A (Pune) + Plant C (Chennai) Dual-Sourcing",
      "recommendedWarehouse": "Warehouse X (Rotterdam) + Warehouse Y (Nhava Sheva)",
      "recommendedRoute": "Route 3 (Hybrid Coastal Rail + Fast Sea)",
      "resilienceScore": 92,
      "totalCost": "$164 / unit ($1.64M/mo)",
      "deliverySLA": "13 Days avg SLA",
      "justification": "Provides 92% network resilience with balanced cost ($164/unit total landed) and 13-day delivery SLA mitigating single-source chokepoint vulnerabilities.",
      "tradeoffAnalysis": "Multi-objective Pareto evaluation shows that spending an additional $30/unit over the leanest alternative eliminates 76% of single-point failure vulnerabilities while avoiding the $54/unit penalty of full air-freight redundancy."
    }
  ],
  "AuditLogs": [
    {
      "ID": "LOG-001",
      "time": "22:04:18",
      "agent": "Sensing Agent",
      "type": "Sensing",
      "color": "cyan",
      "event": "Detected shortfall in SAP S/4HANA PO #88412.",
      "detail": "Supplier X confirmed shipment of only 2,000 units against 5,000 PO quantity (40% fulfillment capacity). Shortfall flagged via S/4HANA EDI message 856.",
      "payload": "{\"po\":\"88412\",\"vendor\":\"SUP-X-DE\",\"material\":\"MC-88\",\"deficit\":\"3,000 units\"}"
    },
    {
      "ID": "LOG-002",
      "time": "22:04:20",
      "agent": "Network Intelligence Agent",
      "type": "Network",
      "color": "blue",
      "event": "Causal propagation across SAP HANA supply graph completed.",
      "detail": "Determined downstream blast radius: Plant A assembly line stops in 48 hours. 12 OEM customer orders delayed. Immediate financial exposure: $1.42M.",
      "payload": "{\"blastRadius\":\"PLANT-A, DIST-GLOBAL\",\"affectedOrders\":12,\"exposure\":\"$1,420,000\"}"
    },
    {
      "ID": "LOG-003",
      "time": "22:04:22",
      "agent": "Production & Sourcing Agents",
      "type": "Domain",
      "color": "purple",
      "event": "Evaluated alternative node readiness in parallel.",
      "detail": "Identified Plant B (Pune, India) operating with +30% available capacity on certified lines. Sourcing agent confirmed Supplier Y spot-buy feasibility.",
      "payload": "{\"plantBReserve\":\"+1,200 units\",\"supplierYLeadTime\":\"3 days\"}"
    },
    {
      "ID": "LOG-004",
      "time": "22:04:24",
      "agent": "Scenario Agent",
      "type": "Scenario",
      "color": "purple",
      "event": "Generated 4 what-if configurations with Monte Carlo simulation.",
      "detail": "Simulated 10,000 iterations for cost, lead time, and customer SLA preservation. Ranked SCN-004 (Hybrid Rebalance) with highest confidence score (96.4%).",
      "payload": "{\"scenariosSimulated\":4,\"optimalScenario\":\"SCN-004\",\"confidenceScore\":0.964}"
    },
    {
      "ID": "LOG-005",
      "time": "22:04:26",
      "agent": "Compliance Safeguard",
      "type": "Compliance",
      "color": "amber",
      "event": "Policy check passed (Cost limit within $50,000 threshold).",
      "detail": "Plan cost: $52,000 within authorized emergency limit. ESG Scope 3 air emissions offset pre-approved under Lufthansa SAF agreement.",
      "payload": "{\"policyRule\":\"CAP_RECOVERY_POL_09\",\"budgetDelta\":\"$52,000\",\"esgApproved\":true}"
    },
    {
      "ID": "LOG-006",
      "time": "22:04:29",
      "agent": "Resilience Memory",
      "type": "Memory",
      "color": "emerald",
      "event": "Decision vectors indexed in SAP HANA Cloud HDI Container.",
      "detail": "Vector embeddings created in SAP HANA Cloud Vector Engine (1536 dims). Pattern matched with 2024 Munich raw material recovery protocol.",
      "payload": "{\"hdiContainer\":\"RESILINK_HDI_DB\",\"vectorDims\":1536,\"patternSimilarity\":0.942}"
    }
  ],
  "DesignMarkets": [
    {
      "ID": "DMKT-EU",
      "name": "Europe (Berlin & Munich EV Cluster)",
      "region": "EMEA",
      "demandMonthly": 6000,
      "slaTargetDays": 14,
      "priority": "P1 - Strategic",
      "revenuePotential": "$4.8M / month"
    },
    {
      "ID": "DMKT-IN",
      "name": "India (Pune & Bengaluru Auto Hub)",
      "region": "APAC",
      "demandMonthly": 4000,
      "slaTargetDays": 10,
      "priority": "P1 - High Growth",
      "revenuePotential": "$2.4M / month"
    },
    {
      "ID": "DMKT-US",
      "name": "North America (Detroit & Austin)",
      "region": "Americas",
      "demandMonthly": 0,
      "slaTargetDays": 21,
      "priority": "P2 - Expansion",
      "revenuePotential": "$3.2M / month"
    }
  ],
  "DesignPlants": [
    {
      "ID": "DPLANT-A",
      "name": "Plant A (Pune Gigafactory)",
      "location": "Pune",
      "country": "IN",
      "type": "Mega Gigafactory",
      "unitOpex": 34,
      "capacity": 8000,
      "leadTimeDays": 5,
      "riskScore": 28,
      "resilienceScore": 86,
      "flexibility": "High",
      "status": "PRIMARY"
    },
    {
      "ID": "DPLANT-B",
      "name": "Plant B (Dresden Precision Fab)",
      "location": "Dresden",
      "country": "DE",
      "type": "Precision Clean Fab",
      "unitOpex": 48,
      "capacity": 5000,
      "leadTimeDays": 3,
      "riskScore": 14,
      "resilienceScore": 94,
      "flexibility": "Medium",
      "status": "CONTINGENCY"
    },
    {
      "ID": "DPLANT-C",
      "name": "Plant C (Chennai Coastal Assembly)",
      "location": "Chennai",
      "country": "IN",
      "type": "Coastal Assembly",
      "unitOpex": 36,
      "capacity": 7500,
      "leadTimeDays": 6,
      "riskScore": 24,
      "resilienceScore": 89,
      "flexibility": "High",
      "status": "SECONDARY"
    }
  ],
  "DesignRoutes": [
    {
      "ID": "DROUTE-1",
      "name": "Route 1 (Multimodal Ocean + Rail)",
      "mode": "Ocean + Rail",
      "origin": "Shenzhen / Nhava Sheva",
      "destination": "Rotterdam",
      "costIndex": "18.00",
      "transitDays": 21,
      "carbonKgPerUnit": 48,
      "riskScore": 54,
      "reliability": "84.00",
      "resilienceScore": 76,
      "status": "CONTINGENCY"
    },
    {
      "ID": "DROUTE-2",
      "name": "Route 2 (Air Freight Express Corridor)",
      "mode": "Air Cargo Express",
      "origin": "BOM / FRA",
      "destination": "Rotterdam & Munich",
      "costIndex": "46.00",
      "transitDays": 4,
      "carbonKgPerUnit": 210,
      "riskScore": 18,
      "reliability": "97.00",
      "resilienceScore": 93,
      "status": "EXPRESS_EXPEDITE"
    },
    {
      "ID": "DROUTE-3",
      "name": "Route 3 (Hybrid Coastal Rail + Fast Sea)",
      "mode": "Hybrid Fast Sea + Rail",
      "origin": "Chennai / Nhava Sheva",
      "destination": "Rotterdam & Dresden",
      "costIndex": "28.00",
      "transitDays": 12,
      "carbonKgPerUnit": 78,
      "riskScore": 26,
      "reliability": "91.00",
      "resilienceScore": 89,
      "status": "PRIMARY_CORRIDOR"
    }
  ],
  "DesignScenarios": [
    {
      "ID": "DSCN-01",
      "name": "Lowest Cost (Lean JIT)",
      "tagline": "Single low-cost sourcing with minimal safety buffer",
      "totalMonthlyCost": "1340000.00",
      "unitLandedCost": "134.00",
      "avgDeliveryDays": "26",
      "riskExposure": "74",
      "resilienceScore": 58,
      "esgRating": "B",
      "carbonMetric": "48 kg CO2e / unit",
      "supplierConfig": "Supplier A (100%)",
      "plantConfig": "Plant A (100%)",
      "warehouseConfig": "Warehouse Y only",
      "routeConfig": "Route 1 Ocean",
      "recommended": false
    },
    {
      "ID": "DSCN-02",
      "name": "Highest Resilience (Fail-Safe)",
      "tagline": "Multi-redundant high-buffer network with air express",
      "totalMonthlyCost": "2180000.00",
      "unitLandedCost": "218.00",
      "avgDeliveryDays": "8",
      "riskExposure": "14",
      "resilienceScore": 98,
      "esgRating": "AAA",
      "carbonMetric": "210 kg CO2e / unit",
      "supplierConfig": "Supplier B (60%) + Supplier C (40%)",
      "plantConfig": "Plant A (40%) + Plant B (30%) + Plant C (30%)",
      "warehouseConfig": "Warehouse X + Warehouse Y",
      "routeConfig": "Route 2 Air Express",
      "recommended": false
    },
    {
      "ID": "DSCN-03",
      "name": "Balanced Network (ResiLink Pareto)",
      "tagline": "AI-optimized multi-echelon trade-off with dynamic backup",
      "totalMonthlyCost": "1640000.00",
      "unitLandedCost": "164.00",
      "avgDeliveryDays": "13",
      "riskExposure": "24",
      "resilienceScore": 92,
      "esgRating": "AA",
      "carbonMetric": "78 kg CO2e / unit",
      "supplierConfig": "Supplier B (75%) + Supplier C (25% backup)",
      "plantConfig": "Plant A (60%) + Plant C (40%)",
      "warehouseConfig": "Warehouse X + Warehouse Y",
      "routeConfig": "Route 3 Hybrid Fast Sea/Rail",
      "recommended": true
    }
  ],
  "DesignSuppliers": [
    {
      "ID": "DSUP-A",
      "name": "Supplier A (Shenzhen Tier-1)",
      "tier": "Tier 1",
      "location": "Shenzhen",
      "country": "CN",
      "costTier": "Low",
      "unitCost": "72.00",
      "riskTier": "High",
      "riskScore": 78,
      "reliability": "74.00",
      "capacity": 15000,
      "leadTimeDays": 28,
      "resilienceScore": 52,
      "geographyRisk": "High Port Congestion & Tariff Volatility",
      "esgRating": "B",
      "status": "BACKUP"
    },
    {
      "ID": "DSUP-B",
      "name": "Supplier B (Munich Advanced Materials)",
      "tier": "Tier 1",
      "location": "Munich",
      "country": "DE",
      "costTier": "Medium",
      "unitCost": "95.00",
      "riskTier": "Low",
      "riskScore": 22,
      "reliability": "94.00",
      "capacity": 12000,
      "leadTimeDays": 14,
      "resilienceScore": 88,
      "geographyRisk": "Low Geopolitical Risk",
      "esgRating": "AA",
      "status": "SELECTED"
    },
    {
      "ID": "DSUP-C",
      "name": "Supplier C (Kyoto Precision Battery)",
      "tier": "Tier 1",
      "location": "Kyoto",
      "country": "JP",
      "costTier": "High",
      "unitCost": "118.00",
      "riskTier": "Very Low",
      "riskScore": 12,
      "reliability": "98.00",
      "capacity": 8000,
      "leadTimeDays": 9,
      "resilienceScore": 95,
      "geographyRisk": "Ultra-low Geopolitical Risk",
      "esgRating": "AAA",
      "status": "QUALIFIED"
    }
  ],
  "DesignWarehouses": [
    {
      "ID": "DWH-X",
      "name": "Warehouse X (Rotterdam Euro Hub)",
      "location": "Rotterdam",
      "country": "NL",
      "storageType": "Automated High-Bay",
      "capacityPallets": 25000,
      "unitStorageCost": "14.00",
      "leadTimeDays": 2,
      "riskScore": 12,
      "resilienceScore": 96,
      "status": "ACTIVE_HUB"
    },
    {
      "ID": "DWH-Y",
      "name": "Warehouse Y (Nhava Sheva Gateway)",
      "location": "Navi Mumbai",
      "country": "IN",
      "storageType": "Bonded Cold Storage & Staging",
      "capacityPallets": 20000,
      "unitStorageCost": "10.00",
      "leadTimeDays": 3,
      "riskScore": 19,
      "resilienceScore": 89,
      "status": "ACTIVE_HUB"
    }
  ],
  "Disruptions": [
    {
      "ID": "DISR-2026-0927",
      "severity": "CRITICAL",
      "sourceNode": "Supplier X (Germany)",
      "impactNode": "Plant A (Stuttgart)",
      "shortfallPct": 40,
      "affectedUnits": 3000,
      "customerOrders": 12,
      "headline": "Supplier X (Germany) delivery shortfall — 40% fulfillment capacity. Impact: Plant A at risk, 3,000 units affected, 12 customer orders pending.",
      "state": "ACTIVE",
      "detectedBy": "SAP S/4HANA Sensing Agent",
      "timestamp": "22:04:18 UTC",
      "estimatedRevenueLoss": "$1,420,000",
      "rootCause": "Tier-2 semiconductor substrate shortage at supplier foundry in North Rhine-Westphalia.",
      "urgency": "HIGH (Action required < 48 hours)"
    }
  ],
  "Nodes": [
    {
      "ID": "SUP-X",
      "name": "Supplier X",
      "category": "Tier-1 Supplier",
      "location": "Düsseldorf, Germany",
      "country": "DE",
      "status": "DISRUPTED",
      "capacity": 40,
      "baselineCapacity": 100,
      "leadTime": "14 Days (Delayed)",
      "material": "Silicon Micro-Controllers (MC-88)",
      "sapPo": "PO #88412",
      "sapStorageLoc": "SLOC_DE_RAW_01",
      "sapPlantCode": null,
      "sapLocation": null,
      "sapContractGroup": null,
      "riskScore": "92/100",
      "activeDeficit": "3,000 units",
      "bufferCapacity": null,
      "allocation": null,
      "x": 100,
      "y": 110,
      "color": "#EF4444"
    },
    {
      "ID": "SUP-Y",
      "name": "Supplier Y (Backup)",
      "category": "Tier-1 Supplier",
      "location": "Katowice, Poland",
      "country": "PL",
      "status": "OPERATIONAL",
      "capacity": 100,
      "baselineCapacity": 100,
      "leadTime": "3 Days (Fast-Track)",
      "material": "Silicon Micro-Controllers (Tier-1 Qualified)",
      "sapPo": "PO-STANDBY-09",
      "sapStorageLoc": "SLOC_PL_SEC_02",
      "sapPlantCode": null,
      "sapLocation": null,
      "sapContractGroup": null,
      "riskScore": "18/100",
      "activeDeficit": "0 units",
      "bufferCapacity": null,
      "allocation": null,
      "x": 100,
      "y": 290,
      "color": "#06B6D4"
    },
    {
      "ID": "PLANT-A",
      "name": "Plant A (Direct Impact)",
      "category": "Manufacturing Plant",
      "location": "Stuttgart, Germany",
      "country": "DE",
      "status": "BOTTLENECKED",
      "capacity": 42,
      "baselineCapacity": 100,
      "leadTime": "12 Days",
      "material": "Automotive Sub-Assembly Unit",
      "sapPo": null,
      "sapStorageLoc": "SLOC_STU_PROD_01",
      "sapPlantCode": "PLANT_1010_EU",
      "sapLocation": null,
      "sapContractGroup": null,
      "riskScore": "85/100",
      "activeDeficit": "3,000 units pending",
      "bufferCapacity": null,
      "allocation": null,
      "x": 370,
      "y": 110,
      "color": "#F59E0B"
    },
    {
      "ID": "PLANT-B",
      "name": "Plant B (Resilience Hub)",
      "category": "Manufacturing Plant",
      "location": "Pune, India",
      "country": "IN",
      "status": "BUFFER_AVAILABLE",
      "capacity": 100,
      "baselineCapacity": 100,
      "leadTime": "2 Days (Express Setup)",
      "material": "Automotive Sub-Assembly Unit",
      "sapPo": null,
      "sapStorageLoc": "SLOC_PUN_PROD_02",
      "sapPlantCode": "PLANT_2020_APAC",
      "sapLocation": null,
      "sapContractGroup": null,
      "riskScore": "12/100",
      "activeDeficit": "0 units",
      "bufferCapacity": "+30% Reserve (+1,200 units)",
      "allocation": "Nominal (Shift 1 & 2 Active)",
      "x": 370,
      "y": 290,
      "color": "#10B981"
    },
    {
      "ID": "WH-UAE",
      "name": "Central Warehouse Hub",
      "category": "Consolidation Center",
      "location": "Dubai Logistics City, UAE",
      "country": "AE",
      "status": "OPERATIONAL",
      "capacity": 92,
      "baselineCapacity": 100,
      "leadTime": "1.5 Days",
      "material": "Cross-Dock Finished Inventory",
      "sapPo": null,
      "sapStorageLoc": null,
      "sapPlantCode": null,
      "sapLocation": "SLOC_DXB_01",
      "sapContractGroup": null,
      "riskScore": "14/100",
      "activeDeficit": "0 units",
      "bufferCapacity": "5,400 units safety stock",
      "allocation": null,
      "x": 640,
      "y": 200,
      "color": "#3B82F6"
    },
    {
      "ID": "DIST-GLOBAL",
      "name": "Global Customer Delivery",
      "category": "Market Endpoints",
      "location": "Frankfurt, Detroit, Tokyo, Singapore",
      "country": "GLOBAL",
      "status": "PENDING_REALLOCATION",
      "capacity": 88,
      "baselineCapacity": 100,
      "leadTime": "1 Day",
      "material": "Global Fleet Shipments",
      "sapPo": null,
      "sapStorageLoc": null,
      "sapPlantCode": null,
      "sapLocation": null,
      "sapContractGroup": "OEM-CONTRACT-AA-900",
      "riskScore": "78/100",
      "activeDeficit": "12 Orders at SLA Penalty Risk",
      "bufferCapacity": null,
      "allocation": null,
      "x": 880,
      "y": 200,
      "color": "#8B5CF6"
    }
  ],
  "Scenarios": [
    {
      "ID": "SCN-001",
      "name": "Wait & Absorb",
      "tag": "Passive Acceptance",
      "subtitle": "Accept delays",
      "description": "Accept Supplier X delayed delivery schedule. Pause Plant A production line until replenishment arrives in 14 days.",
      "cost": "Low ($12,000)",
      "costValue": 12000,
      "time": "14 Days",
      "days": 14,
      "risk": "High (88%)",
      "riskLevel": "high",
      "sla": "42%",
      "slaValue": 42,
      "financialImpact": "-$840,000 SLA Penalties",
      "carbonDelta": "0 kg CO2e (Baseline)",
      "recommended": false,
      "badge": null,
      "lossMitigation": "0%"
    },
    {
      "ID": "SCN-002",
      "name": "Alternate Supplier Y",
      "tag": "Spot Buy Procurement",
      "subtitle": "Expedite PO",
      "description": "Expedite spot buy purchase order to Supplier Y in Poland with emergency premium tooling and expedited trucking.",
      "cost": "High ($94,000)",
      "costValue": 94000,
      "time": "3 Days",
      "days": 3,
      "risk": "Med (45%)",
      "riskLevel": "med",
      "sla": "91%",
      "slaValue": 91,
      "financialImpact": "-$180,000 Procurement Delta",
      "carbonDelta": "+1,400 kg CO2e (Road Freight)",
      "recommended": false,
      "badge": null,
      "lossMitigation": "+42%"
    },
    {
      "ID": "SCN-003",
      "name": "Inventory Reallocation",
      "tag": "Buffer Liquidation",
      "subtitle": "Draw from UAE",
      "description": "Deplete Central Warehouse (UAE) safety buffer and reallocate inventory slated for Latin America regional market.",
      "cost": "Med ($48,000)",
      "costValue": 48000,
      "time": "2 Days",
      "days": 2,
      "risk": "Low (28%)",
      "riskLevel": "low",
      "sla": "88%",
      "slaValue": 88,
      "financialImpact": "-$120,000 Redistribution",
      "carbonDelta": "+850 kg CO2e (Air Transfer)",
      "recommended": false,
      "badge": null,
      "lossMitigation": "+54%"
    },
    {
      "ID": "SCN-004",
      "name": "RESILINK Hybrid Plan",
      "tag": "Autonomous Rebalance",
      "subtitle": "Shift 1,000 units Plant A → Plant B + Express Air Freight",
      "description": "Leverage Plant B (India) reserve capacity (+30%) to assemble 1,000 units, paired with Lufthansa Express Air to UAE hub, and rebalance buffer.",
      "cost": "Balanced ($52,000)",
      "costValue": 52000,
      "time": "2 Days",
      "days": 2,
      "risk": "Very Low (8%)",
      "riskLevel": "very-low",
      "sla": "96%",
      "slaValue": 96,
      "financialImpact": "+$680,000 Loss Mitigation",
      "carbonDelta": "+420 kg CO2e (Optimized Belly Cargo)",
      "recommended": true,
      "badge": "Recommended Strategy (+68% Loss Mitigation)",
      "lossMitigation": "+68%"
    }
  ]
};
