namespace resilink;

using { cuid, managed } from '@sap/cds/common';

/**
 * SAP HANA Master Data Entity: Supply Chain Network Nodes
 */
entity Nodes {
  key ID               : String(32);
      name             : String(100);
      category         : String(50);
      location         : String(100);
      country          : String(10);
      status           : String(30); // DISRUPTED, BOTTLENECKED, BUFFER_AVAILABLE, OPERATIONAL, REBALANCED, STABILIZED
      capacity         : Integer;
      baselineCapacity : Integer default 100;
      leadTime         : String(50);
      material         : String(100);
      sapPo            : String(50);
      sapStorageLoc    : String(50);
      sapPlantCode     : String(50);
      sapLocation      : String(50);
      sapContractGroup : String(50);
      riskScore        : String(20);
      activeDeficit    : String(50);
      bufferCapacity   : String(50);
      allocation       : String(100);
      x                : Integer;
      y                : Integer;
      color            : String(20);
}

/**
 * Critical Disruption Events detected by Sensing Agents
 */
entity Disruptions {
  key ID                   : String(32);
      severity             : String(20); // CRITICAL, WARNING, INFO
      sourceNode           : String(100);
      impactNode           : String(100);
      shortfallPct         : Integer;
      affectedUnits        : Integer;
      customerOrders       : Integer;
      headline             : LargeString;
      state                : String(20); // ACTIVE, RESOLVED
      detectedBy           : String(100);
      timestamp            : String(50);
      estimatedRevenueLoss : String(50);
      rootCause            : LargeString;
      urgency              : String(50);
}

/**
 * Simulated What-If Scenarios generated by Generative AI Scenario Agents
 */
entity Scenarios {
  key ID              : String(32);
      name            : String(100);
      tag             : String(50);
      subtitle        : String(150);
      description     : LargeString;
      cost            : String(50);
      costValue       : Decimal(12, 2);
      time            : String(30);
      days            : Integer;
      risk            : String(30);
      riskLevel       : String(20); // very-low, low, med, high
      sla             : String(20);
      slaValue        : Decimal(5, 2);
      financialImpact : String(100);
      carbonDelta     : String(100);
      recommended     : Boolean default false;
      badge           : String(100);
      lossMitigation  : String(20);
}

/**
 * Immutable Audit Logs & Multi-Agent Reasoning Chain
 */
entity AuditLogs {
  key ID      : String(32);
      time    : String(20);
      agent   : String(50);
      type    : String(30); // Sensing, Network, Domain, Scenario, Compliance, Execution, Memory
      color   : String(20);
      event   : String(200);
      detail  : LargeString;
      payload : LargeString; // JSON serialized payload
}

/**
 * Historical Resilience Runs logged into SAP HANA Cloud Vector Store
 */
entity ResilienceRuns : cuid, managed {
  scenarioId          : String(32);
  targetPlant         : String(50);
  volumeUnits         : Integer;
  carrier             : String(100);
  status              : String(30);
  scoreDelta          : String(20);
  transactionId       : String(50);
  projectedSLA        : Decimal(5, 2);
  vectorEmbeddingRef  : String(100);
}

/**
 * ========================================================
 * BUILD MODULE: INTELLIGENT SUPPLY NETWORK DESIGN ENTITIES
 * ========================================================
 */

/**
 * Master Supply Network Design Specification
 */
entity NetworkDesigns {
  key ID                   : String(32);
      name                 : String(100);
      product              : String(100);
      demandVolume         : Integer;
      demandUnit           : String(30);
      targetMarkets        : String(200);
      maxCostBudget        : Decimal(12, 2);
      requiredDeliveryDays : Integer;
      qualityTier          : String(50);
      riskTolerance        : String(30);
      status               : String(30); // DRAFT, COMMITTED_BASELINE, ACTIVE
      selectedScenario     : String(50);
      resilienceScore      : Decimal(5, 2);
      totalMonthlyCost     : Decimal(12, 2);
}

/**
 * Candidate Suppliers for Evaluation
 */
entity DesignSuppliers {
  key ID              : String(32);
      name            : String(100);
      tier            : String(20);
      location        : String(100);
      country         : String(10);
      costTier        : String(20); // Low, Medium, High
      unitCost        : Decimal(10, 2);
      riskTier        : String(20); // Low, Medium, High, Very Low
      riskScore       : Integer;
      reliability     : Decimal(5, 2);
      capacity        : Integer;
      leadTimeDays    : Integer;
      resilienceScore : Decimal(5, 2);
      geographyRisk   : String(50);
      esgRating       : String(10);
      status          : String(30); // SELECTED, QUALIFIED, BACKUP
}

/**
 * Candidate Manufacturing Plants
 */
entity DesignPlants {
  key ID              : String(32);
      name            : String(100);
      location        : String(100);
      country         : String(10);
      type            : String(50); // Mega Gigafactory, Precision Fab, Assembly
      unitOpex        : Decimal(10, 2);
      capacity        : Integer;
      leadTimeDays    : Integer;
      riskScore       : Integer;
      resilienceScore : Decimal(5, 2);
      flexibility     : String(30);
      status          : String(30); // PRIMARY, SECONDARY, CONTINGENCY
}

/**
 * Candidate Warehouses & Distribution Hubs
 */
entity DesignWarehouses {
  key ID              : String(32);
      name            : String(100);
      location        : String(100);
      country         : String(10);
      storageType     : String(50);
      capacityPallets : Integer;
      unitStorageCost : Decimal(10, 2);
      leadTimeDays    : Integer;
      riskScore       : Integer;
      resilienceScore : Decimal(5, 2);
      status          : String(30); // ACTIVE_HUB, BUFFER_RESERVE
}

/**
 * Transportation Corridors & Routes
 */
entity DesignRoutes {
  key ID              : String(32);
      name            : String(100);
      mode            : String(50); // Multimodal Ocean+Rail, Air Freight, Coastal Rail
      origin          : String(100);
      destination     : String(100);
      costIndex       : Decimal(10, 2);
      transitDays     : Integer;
      carbonKgPerUnit : Decimal(8, 2);
      riskScore       : Integer;
      reliability     : Decimal(5, 2);
      resilienceScore : Decimal(5, 2);
      status          : String(30); // PRIMARY_CORRIDOR, EXPRESS_EXPEDITE
}

/**
 * Target Markets
 */
entity DesignMarkets {
  key ID               : String(32);
      name             : String(100);
      region           : String(50);
      demandMonthly    : Integer;
      slaTargetDays    : Integer;
      priority         : String(20);
      revenuePotential : String(50);
}

/**
 * Network Design Scenarios for Trade-off Comparison
 */
entity DesignScenarios {
  key ID               : String(32);
      name             : String(100);
      tagline          : String(100);
      totalMonthlyCost : Decimal(12, 2);
      unitLandedCost   : Decimal(10, 2);
      avgDeliveryDays  : Integer;
      riskExposure     : Integer;
      resilienceScore  : Decimal(5, 2);
      esgRating        : String(10);
      carbonMetric     : String(50);
      supplierConfig   : String(100);
      plantConfig      : String(100);
      warehouseConfig  : String(100);
      routeConfig      : String(100);
      recommended      : Boolean default false;
}

/**
 * Generative AI Recommendation
 */
entity AIRecommendations {
  key ID                   : String(32);
      title                : String(100);
      recommendedSupplier  : String(100);
      recommendedPlant     : String(100);
      recommendedWarehouse : String(100);
      recommendedRoute     : String(100);
      resilienceScore      : Decimal(5, 2);
      totalCost            : String(50);
      deliverySLA          : String(50);
      justification        : LargeString;
      tradeoffAnalysis     : LargeString;
}

/**
 * ========================================================
 * CANONICAL OPERATIONAL SUPPLY CHAIN DATABASE ENTITIES
 * (Company, Supplier, Plant, Warehouse, Inventory, Orders, Shipment, Routes, Customer Markets)
 * ========================================================
 */

/**
 * Enterprise Organizations & Supply Chain Owners
 */
entity Companies {
  key ID              : String(32);
      name            : String(100);
      code            : String(50);
      city            : String(100);
      country         : String(10);
      industry        : String(100);
      resilienceScore : Decimal(5, 2);
      status          : String(30); // ACTIVE, ONBOARDING
}

/**
 * Global Tier-1 & Tier-2 Suppliers
 */
entity Suppliers {
  key ID               : String(32);
      name             : String(100);
      location         : String(100);
      country          : String(10);
      material         : String(100);
      capacity         : Integer;
      baselineCapacity : Integer default 100;
      reliability      : Decimal(5, 2);
      riskScore        : String(20);
      leadTimeDays     : Integer;
      unitCost         : Decimal(10, 2);
      status           : String(30); // OPERATIONAL, DISRUPTED, BUFFER_AVAILABLE
}

/**
 * Manufacturing & Assembly Plants
 */
entity Plants {
  key ID                 : String(32);
      name               : String(100);
      location           : String(100);
      country            : String(10);
      productionCapacity : Integer;
      utilizationPct     : Decimal(5, 2);
      leadTimeDays       : Integer;
      riskScore          : String(20);
      status             : String(30); // OPERATIONAL, BOTTLENECKED, SURGING
}

/**
 * Regional Warehouses & Distribution Hubs
 */
entity Warehouses {
  key ID              : String(32);
      name            : String(100);
      location        : String(100);
      country         : String(10);
      storageCapacity : Integer;
      currentStock    : Integer;
      bufferCapacity  : Integer;
      status          : String(30); // CONNECTED, HIGH_STOCK, BUFFER_RESERVE
      riskScore       : String(20);
}

/**
 * Real-time SKU Inventory Levels & Buffer Stock
 */
entity Inventory {
  key ID                 : String(32);
      material           : String(100);
      plantOrWarehouseId : String(32);
      availableStock     : Integer;
      reservedStock      : Integer;
      safetyStock        : Integer;
      reorderPoint       : Integer;
      demandUnits        : Integer;
      unit               : String(20);
      status             : String(30); // AVAILABLE, LOW_STOCK, BUFFERED
}

/**
 * Active Customer & OEM Orders
 */
entity Orders {
  key ID                    : String(32);
      orderNumber           : String(50);
      customerName          : String(100);
      product               : String(100);
      quantity              : Integer;
      status                : String(30); // Completed, Pending, Delayed
      promisedDate          : Date;
      estimatedDeliveryDate : Date;
      slaCompliance         : Decimal(5, 2);
}

/**
 * In-Transit & Scheduled Freight Shipments
 */
entity Shipments {
  key ID             : String(32);
      shipmentNumber : String(50);
      originNode     : String(100);
      destinationNode: String(100);
      carrier        : String(100);
      transportMode  : String(50);
      status         : String(30); // Delivered, In Transit, Delayed
      eta            : String(50);
      trackingCode   : String(50);
      delayRisk      : String(20);
}

/**
 * Multimodal Transport Routes & Corridors
 */
entity Routes {
  key ID            : String(32);
      name          : String(100);
      origin        : String(100);
      destination   : String(100);
      transportMode : String(50);
      transitDays   : Integer;
      costIndex     : Decimal(10, 2);
      carbonKg      : Decimal(8, 2);
      reliability   : Decimal(5, 2);
      riskScore     : String(20);
      status        : String(30); // ACTIVE, REROUTED, CONGESTED
}

/**
 * Target Customer Markets & Regional Demands
 */
entity CustomerMarkets {
  key ID                : String(32);
      name              : String(100);
      region            : String(50);
      country           : String(10);
      demandMonthly     : Integer;
      targetSLA         : Integer;
      slaPerformance    : Decimal(5, 2);
      activeOrdersCount : Integer;
      priority          : String(20);
}


