namespace resilink;

using { cuid, managed } from '@sap/cds/common';

/**
 * SAP HANA Master Data Entity: Supply Chain Network Nodes
 */
entity Nodes {
  key ID               : String(32);
      name             : String(100);
      category         : String(50);
      location         : String(100);
      country          : String(10);
      status           : String(30); // DISRUPTED, BOTTLENECKED, BUFFER_AVAILABLE, OPERATIONAL, REBALANCED, STABILIZED
      capacity         : Integer;
      baselineCapacity : Integer default 100;
      leadTime         : String(50);
      material         : String(100);
      sapPo            : String(50);
      sapStorageLoc    : String(50);
      sapPlantCode     : String(50);
      sapLocation      : String(50);
      sapContractGroup : String(50);
      riskScore        : String(20);
      activeDeficit    : String(50);
      bufferCapacity   : String(50);
      allocation       : String(100);
      x                : Integer;
      y                : Integer;
      color            : String(20);
}

/**
 * Critical Disruption Events detected by Sensing Agents
 */
entity Disruptions : managed {
  key ID                   : String(32);
      severity             : String(20); // CRITICAL, WARNING, INFO
      sourceNode           : String(100);
      impactNode           : String(100);
      shortfallPct         : Integer;
      affectedUnits        : Integer;
      customerOrders       : Integer;
      headline             : LargeString;
      state                : String(20); // ACTIVE, RESOLVED
      detectedBy           : String(100);
      timestamp            : String(50);
      estimatedRevenueLoss : String(50);
      rootCause            : LargeString;
      urgency              : String(50);
}

/**
 * Simulated What-If Scenarios generated by Generative AI Scenario Agents
 */
entity Scenarios {
  key ID              : String(32);
      name            : String(100);
      tag             : String(50);
      subtitle        : String(150);
      description     : LargeString;
      cost            : String(50);
      costValue       : Decimal(12, 2);
      time            : String(30);
      days            : Integer;
      risk            : String(30);
      riskLevel       : String(20); // very-low, low, med, high
      sla             : String(20);
      slaValue        : Decimal(5, 2);
      financialImpact : String(100);
      carbonDelta     : String(100);
      recommended     : Boolean default false;
      badge           : String(100);
      lossMitigation  : String(20);
}

/**
 * Immutable Audit Logs & Multi-Agent Reasoning Chain
 */
entity AuditLogs {
  key ID      : String(32);
      time    : String(20);
      agent   : String(50);
      type    : String(30); // Sensing, Network, Domain, Scenario, Compliance, Execution, Memory
      color   : String(20);
      event   : String(200);
      detail  : LargeString;
      payload : LargeString; // JSON serialized payload
}

/**
 * Historical Resilience Runs logged into SAP HANA Cloud Vector Store
 */
entity ResilienceRuns : cuid, managed {
  scenarioId          : String(32);
  targetPlant         : String(50);
  volumeUnits         : Integer;
  carrier             : String(100);
  status              : String(30);
  scoreDelta          : String(20);
  transactionId       : String(50);
  projectedSLA        : Decimal(5, 2);
  vectorEmbeddingRef  : String(100);
}
